package com.company;

public class vishal_practice {
    public static void main(String[] args) {
    /*    System.out.println("--Boolean");
        boolean b1 =true;
        boolean b2 =false;
        if(b1)
            System.out.println("if part true");
            else
            System.out.println("Else part");
            Boolean b5=true;
            Boolean b6=false;
            if(b5)
                System.out.println("b5 is Boolean ref. type");
            else
                System.out.println("else part");
            char ch1=65535;
            char ch2= '7';
        System.out.println(ch1);
        System.out.println(ch2);
        System.out.println("\n--------");
       for(char ch=0;ch<255;ch++){
           int x=ch;
            System.out.print(x);
            System.out.println('\t');
                    System.out.println(ch);
            System.out.println();
        }
String st1="";
String st2="A";
String st3="some abcd%^(&";
        System.out.println(st1);
        System.out.println(st2);
        System.out.println(st3);
        String st4="N65M\u00cfTR";
        System.out.println(st4);
        String st5="D:\test\b40\new";
        System.out.println(st5);
        String st6 ="HELLO\r";
        System.out.println(st6);
        String st7="D:\\core\\pack\\java";
        System.out.println(st7);

long ab=21474836478L;
        System.out.println(ab);
        System.out.println(2147483647+100);
        long l1 =45258l;
        System.out.println(l1);
        System.out.println(Byte.MIN_VALUE);
        System.out.println(Byte.MAX_VALUE);
        System.out.println(Short.MIN_VALUE);
        System.out.println(Short.MAX_VALUE);
       // System.out.println(Short.MIN_VALUE);
        System.out.println(Long.MAX_VALUE);
        System.out.println(Long.MIN_VALUE);
        System.out.println(Integer.MAX_VALUE);
        System.out.println(Integer.MIN_VALUE);
        System.out.println(Float.MIN_VALUE);
        System.out.println(Float.MAX_VALUE);
        System.out.println(Double.MIN_VALUE);
        System.out.println(Double.MAX_VALUE);
        System.out.println("\n---OCTAL---");
        byte a=33;
        System.out.println(a);
        int b =98987789;
        System.out.println(b);
        System.out.println("\n---hexa---");
        int rt1=0xb;
        System.out.println(rt1);
        int abc= 87678;
        String bin =Integer.toBinaryString(abc);
        String oct=Integer.toOctalString(abc);
        String hx=Integer.toHexString(abc);
        System.out.println(bin);
        System.out.println(oct);
        System.out.println(hx);
        System.out.printf("\n%d%o%x",abc,abc,abc);
        System.out.println();
        System.out.println(Math.PI);
double d1=654.7822;
double d2=65.477822e2;
double d3=654778.22e-2;
        System.out.println(d1);
        System.out.println(d2);
        System.out.println(d3);
        double d4=123.456d;
        System.out.println(d4);
        float f1=1.23456e2f;
        System.out.println(f1);
        String st =null;
         int arr[]=null;
         Integer in=null;
        // jtc6 test=null;
        System.out.println(st);
        System.out.println(arr);
        System.out.println(in);
        int aa=97;
        System.out.println(aa);
        int a=+aa;
        System.out.println(a);
        int b=-aa;
        System.out.println(b);
        int c=-b;
        System.out.println(c);
        int d=--aa;
        System.out.println(d);
        int e=-(-aa);
        System.out.println(e);
        System.out.println(aa);
        int f=--aa;
        System.out.println(aa);
        int mn=-56;
        System.out.println(+mn);
        System.out.println(--mn);
        System.out.println(-(-mn));
        System.out.println(--mn);
        char ch='A';
        char ch2=ch;
        int xy=+ch;
        System.out.println(xy);
        byte by1=46;
        byte by2=+46;
        int by4=+by1;
        System.out.println(by4);
        byte by1=10+20;
        System.out.println(by1);
       final int by2=10;
final int by3=20;
  byte by4=by2+by3;
        System.out.println(by4);
        char ch1=65;
        char ch2=10;
        int res =ch1+ch2;
        System.out.println(res);
        byte b1=10;
        float ab1=12l+12.0f;
        System.out.println(ab1);
        System.out.println(10/3);
        System.out.println(10.0f/3);
        System.out.println(10.0/3);
        System.out.println(0.0==-0.0);
        System.out.println(10.0/0.0);
        System.out.println(10.0/-0.0);
        System.out.println(0.0/0.0);
        System.out.println(Double.POSITIVE_INFINITY);
        System.out.println(Double.NEGATIVE_INFINITY);
        System.out.println(Double.NaN);
        System.out.println(10/0);
        String st1="ok";
        String st2="jtc";
        String st3=st1+st2;
        System.out.println(st3);
        int ab=10;
        String st4=st1+ab;
        System.out.println(st4);
        String st5=st1+124.251;
        System.out.println(st5);
        String st6=1234.567+st1;
        System.out.println(st6);
        System.out.println(90+45);
        System.out.println("Result is "+90+45);
        System.out.println("result is "+(90+45));
        System.out.println(90+45+ "is result");*/
        System.out.println(90-45);
        System.out.println("result is "+(90-45));
        System.out.println(+90+45+"is result");
      //  System.out.println(90-45);
        int xy =89;
        int mn=67;
        System.out.println("result is"+(xy-mn));
        System.out.println("result is"+xy+(-mn));
        System.out.println("result is"+xy+-mn);
        int cd=10;
        String res =""+cd;
        String res1=cd+"";
        System.out.println(res);
        int ab=90;
        final int yz;
        yz=89;
        ab=67;
        int te =12+20*2/10;
        System.out.println(te);
        boolean b1=23>34;
        System.out.println(b1);
        char ch='A';
        int m=ch;
        byte by1=78;
        int x=by1;
        long val=x;
        double d1=12345;
        final int RT=110;
       final int a1=12;
       final int a2=12;
        byte by3=a1+a2;



    }
}
