package com.company;

public class vishal_jtc_practice2 {
    public static void main(String[] args) {


      /*  int ab = 5678763;
        int res1 = ~ab;
        String bin1 = Integer.toBinaryString(ab);
        String bin2 = Integer.toBinaryString(res1);
        System.out.println(ab);
        System.out.println(bin1);
        System.out.println(bin2);
        int bc=-723765342;
        int res2=~bc;
        String bin3=Integer.toBinaryString(bc);
        String bin4=Integer.toBinaryString(res2);
        System.out.println(bc);
        System.out.println(bin3);
        System.out.println(res2);
        System.out.println(bin4);
        int ab=10;
        int bc=20;
        int res1=true?ab:bc;
        int res2=false?ab:bc;
        System.out.println(res1);
        System.out.println(res2);
        int res3=(ab>bc)?ab:bc;
        System.out.println(res3);
        double res7=(ab>bc)?10.0:bc;
        System.out.println(res7);
        Object obj=(ab>bc)?ab:"twenty";
        System.out.println(obj);
        int a=90;
        int b=456;
        int c=34;
        int max=(a>b)?((a>c)?a:c):((b>c)?b:c);
        System.out.println(max);
        int xy=19;
        byte by1=(byte)xy;
        System.out.println(by1);
        int p=65;
        char ch=(char)p;
        System.out.println(ch);
        int mn=(int)123.456;
        System.out.println(mn);
        int rt=5476;
        byte by4=(byte)rt;
        System.out.println(by4);
        long val=5476;
        byte by5=(byte)val;
        System.out.println(by5);
        int bd=300;
        byte by6=(byte)bd;
        System.out.println(by6);
        int de=428;
        byte by7=(byte)de;
        System.out.println(by7);
        byte r1=10;
        byte r2=20;
        byte r4=(byte)(r1+r2);
        System.out.println(r4);
        int n1=(int)true;
        int ab=100;
        ab++;
        System.out.println(ab);
        int m=13;
        ++m;
        System.out.println(m);
        System.out.println("----");
        int y=13;
        int r1=y++;
        System.out.println(r1+"\t"+y);
        int z=13;
        int r2=++z;
        System.out.println(r2+"\t"+z);
        System.out.println("-----");
        int rt=13;
        rt=++rt;
        System.out.println("rt\t:"+rt);
        System.out.println("-----");
        int qw=13;
        System.out.println("qw++"+qw++);
        System.out.println("qw\t:"+qw);
        System.out.println("----");
        int np = 13;
        int tmp = np++;
        np = tmp;
        System.out.println("NP\t:" + np);
        System.out.println("-----");
        int ad = 13;
        ad = ad++;
        ad = ad++;
        ad = ad++;
        ad = ad++;
        System.out.println("AD\t:"+ad);
        System.out.println("-----");
        int val=12;
        int result =val++ + val++ + val++;
        System.out.println(result);
        System.out.println(val);
        System.out.println(10>78);
        System.out.println(10>=78);
        System.out.println(10>=10);
        System.out.println(10<78);
        System.out.println(10<=78);
        System.out.println(10<=10);
        System.out.println(65==65);
        System.out.println(65==65l);
        System.out.println(65==65.0f);
        System.out.println(65==65.0);
        System.out.println(65=='A');
        System.out.println(true==true);
        System.out.println(true==false);
        String str="1";
        String st1="jtc";
        String st2="jtc";
        String st3=new String("jtc");
        System.out.println(st1+"\t"+st2+"\t"+st3);
        System.out.println(st1==st2);
        System.out.println(st1==st3);
        String str="ABC";
        String test=new String();
        Object obj=str;
        System.out.println(obj==str);
        System.out.println(obj==test);
        obj=test;
        System.out.println("----");
        System.out.println(obj==test);
        System.out.println(obj==str);
        System.out.println(20/2==40/4);
        System.out.println(0.0/0.0!=0.0/0.0);
        System.out.println(Float.NaN!=Float.NaN);
        int ab=10;
        System.out.println("X="+ab=="X="+ab);
        final int xy=10;
        System.out.println("x="+xy=="x="+xy);
        int res=90;
        boolean b1=(res==90);
        boolean b2=(res!=90);
        boolean b3=!b1;
        System.out.println(b1);
        System.out.println(b2);
        System.out.println(b3);
        System.out.println("--LOGICAL AND--");
        int ab =14;
        int xy=14;
        boolean b4=ab<16&&xy++<4;
        System.out.println(b4+"\t"+xy);
        System.out.println("---LOGICAL OR---");
        int mn =14;
        boolean b6=mn<16||mn++<4;
        System.out.println(b6+"\t"+mn);
        int bd=14;
        boolean b7=bd>16||bd++<4;
        System.out.println(b7+"\t"+bd);
        int ab=8;
        int bc=12;
        System.out.println(ab);
        System.out.println(bc);
        System.out.println(true&false);
        System.out.println(false&true);
        int res1=ab&bc;
        System.out.println(res1);
        System.out.println(Integer.toBinaryString(res1));
        int m=123;
        boolean b1=m<100&m++>10;
        System.out.println(m);
        System.out.println(true|false);
        System.out.println(false|false);
        int res2=ab|bc;
        System.out.println(res2);
        System.out.println(Integer.toBinaryString(res2));*/

int ab=64;
        System.out.println(ab<<0);
        System.out.println(ab<<2);
        System.out.println(ab<<3);
        System.out.println(ab<<20);
        System.out.println(ab<<32);
        System.out.println(ab<<35);
        System.out.println(7514l<<34);
        System.out.println(7514l<<35);
        System.out.println(7514l<<64);
        System.out.println("--->>+ ve value---");
        System.out.println(746238>>0);
        System.out.println(746238>>3);
        System.out.println(746238>>6);
        System.out.println(746238>>32);
        System.out.println(746238>>35);
        System.out.println("---->>-ve value-----");
        System.out.println(-1248547>>0);
        System.out.println(-1248547>>3);
        System.out.println(-1248547>>6);
        System.out.println(-1248547>>32);
        System.out.println(-1248547>>35);
        System.out.println("--->>>+ve value---");
        System.out.println(746238>>>0);
        System.out.println(746238>>>3);
        System.out.println(746238>>>6);
        System.out.println(746238>>>32);
        System.out.println(746238>>>35);
        System.out.println("-->>>-ve value----");
        System.out.println(-1248547>>>0);
        System.out.println(-1248547>>>1);
        System.out.println(-1248547>>>3);
        System.out.println(-1248547>>>6);
        System.out.println(-124857>>>32);
        System.out.println(-124857>>>35);









    }
}